/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasisekolah;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
// Import untuk iText PDF
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.Element;
import com.itextpdf.text.BaseColor; // Opsional, jika ingin mengatur warna
import com.itextpdf.text.pdf.BaseFont; // <-- PENTING: Untuk mengatasi error HELVETICA
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import com.itextpdf.text.DocumentException;
import javax.swing.JFileChooser;

/**
 *
 * @author NCEX'S
 */
public class FormMahasiswa extends javax.swing.JFrame {
    // Variabel koneksi dan model tabel
    private Connection conn;
    private final DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMahasiswa.class.getName());

    /**
     * Creates new form FormMahasiswa
     */
        public FormMahasiswa() {
        initComponents();
        
        koneksiDatabase(); // 1. Hubungkan database
        
        // 2. Atur judul kolom tabel
        model = new DefaultTableModel();
        TBmahasiswa.setModel(model);
        model.addColumn("NIM");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Kota");
        
        tampilkanData(); // 3. Munculkan datanya
    }
        
        private void koneksiDatabase() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/sekolah"; 
            String user = "root";
            String pass = ""; 
            conn = DriverManager.getConnection(url, user, pass);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal: " + e.getMessage());
        }
    }

    private void tampilkanData() {
        model.setRowCount(0); // Reset tabel biar bersih dulu
        try {
            String sql = "SELECT * FROM mahasiswa";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                Object[] row = {
                    rs.getString("nim"),
                    rs.getString("nama"),
                    rs.getString("alamat"),
                    rs.getString("kota")
                };
                model.addRow(row); // Masukkan data ke tabel
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Tampil Data: " + e.getMessage());
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFnim = new javax.swing.JTextField();
        TFnama = new javax.swing.JTextField();
        TFalamat = new javax.swing.JTextField();
        TFkota = new javax.swing.JTextField();
        BTsimpan = new javax.swing.JButton();
        BTedit = new javax.swing.JButton();
        BThapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBmahasiswa = new javax.swing.JTable();
        BTcetakpdf = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA MAHASISWA");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("Kota");

        TFnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnimActionPerformed(evt);
            }
        });

        BTsimpan.setText("Simpan");
        BTsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsimpanActionPerformed(evt);
            }
        });

        BTedit.setText("Edit");
        BTedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTeditActionPerformed(evt);
            }
        });

        BThapus.setText("Hapus");
        BThapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThapusActionPerformed(evt);
            }
        });

        TBmahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBmahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBmahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBmahasiswa);

        BTcetakpdf.setText("Cetak PDF");
        BTcetakpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcetakpdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TFnama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFalamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFkota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BTsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(BTedit)
                                .addGap(18, 18, 18)
                                .addComponent(BThapus)
                                .addGap(18, 18, 18)
                                .addComponent(BTcetakpdf))
                            .addComponent(TFnim))))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TFnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTsimpan)
                    .addComponent(BTedit)
                    .addComponent(BThapus)
                    .addComponent(BTcetakpdf))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnimActionPerformed
        // TODO add your handling code here:\
    }//GEN-LAST:event_TFnimActionPerformed

    private void BTsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsimpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO mahasiswa (nim, nama, alamat, kota) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            // Ambil data dari kotak input
            pst.setString(1, TFnim.getText());
            pst.setString(2, TFnama.getText());
            pst.setString(3, TFalamat.getText());
            pst.setString(4, TFkota.getText());
            
            pst.executeUpdate(); // Jalankan perintah simpan
            
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
            
            tampilkanData(); // Refresh tabel agar data baru muncul
            bersihkanForm(); // Kosongkan form
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_BTsimpanActionPerformed

    private void BThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThapusActionPerformed
        // TODO add your handling code here:
        try {
        String nim = TFnim.getText();
        
        if (nim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus dari tabel.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konfirmasi Hapus
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data NIM: " + nim + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM mahasiswa WHERE nim = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            // Set NIM yang akan dihapus
            pst.setString(1, nim);
            
            pst.executeUpdate(); // Jalankan perintah hapus
            
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
            
            tampilkanData(); // Refresh tabel
            bersihkanForm(); // Kosongkan form
        }
        
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
    }
    }//GEN-LAST:event_BThapusActionPerformed

    private void TBmahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBmahasiswaMouseClicked
        // TODO add your handling code here:                                        
    // Ambil baris yang dipilih
    int baris = TBmahasiswa.getSelectedRow();
    
    // Ambil data dari model tabel
    String nim = model.getValueAt(baris, 0).toString();
    String nama = model.getValueAt(baris, 1).toString();
    String alamat = model.getValueAt(baris, 2).toString();
    String kota = model.getValueAt(baris, 3).toString();
    
    // Tampilkan data ke Text Field
    TFnim.setText(nim);
    TFnama.setText(nama);
    TFalamat.setText(alamat);
    TFkota.setText(kota);
    
    // Nonaktifkan input NIM agar tidak bisa diubah saat Edit
    TFnim.setEditable(false);
    }//GEN-LAST:event_TBmahasiswaMouseClicked

    private void BTeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTeditActionPerformed
        // TODO add your handling code here:
        try {
        String nimLama = TFnim.getText(); // NIM diambil dari Text Field yang dinonaktifkan
        String namaBaru = TFnama.getText();
        String alamatBaru = TFalamat.getText();
        String kotaBaru = TFkota.getText();
        
        if (nimLama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit dari tabel.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "UPDATE mahasiswa SET nama = ?, alamat = ?, kota = ? WHERE nim = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        
        // Set nilai baru
        pst.setString(1, namaBaru);
        pst.setString(2, alamatBaru);
        pst.setString(3, kotaBaru);
        // Set kondisi WHERE (berdasarkan NIM lama)
        pst.setString(4, nimLama);
        
        pst.executeUpdate(); // Jalankan perintah update
        
        JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui!");
        
        tampilkanData(); // Refresh tabel
        bersihkanForm(); // Kosongkan form
        
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal Edit: " + e.getMessage());
    }
    }//GEN-LAST:event_BTeditActionPerformed

    private void BTcetakpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcetakpdfActionPerformed
        // TODO add your handling code here:
        // Tentukan lokasi penyimpanan file
    String path = "";
    JFileChooser j = new JFileChooser();
    j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    
    int result = j.showSaveDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        path = j.getSelectedFile().getPath();
    } else {
        return; // Batal jika pengguna tidak memilih folder
    }

    Document doc = new Document();
    
    try {
        // Tentukan output file
        PdfWriter.getInstance(doc, new FileOutputStream(path + "\\LaporanMahasiswa.pdf"));
        doc.open();

        // **KOREKSI FONT DI SINI**
        
        // 1. Definisikan BaseFont (HELVETICA)
        BaseFont bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.EMBEDDED);
        
        // 2. Buat objek Font yang menggunakan BaseFont
        Font titleFont = new Font(bf, 16, Font.BOLD);
        
        // 3. Gunakan Font object untuk Judul
        Paragraph title = new Paragraph("LAPORAN DATA MAHASISWA", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);
        doc.add(new Paragraph("\n"));

        // 4. Buat Tabel (4 kolom)
        PdfPTable tbl = new PdfPTable(4); 
        tbl.setWidthPercentage(100);
        
        // Set Font untuk Header Tabel (bisa menggunakan Font object baru)
        Font headerFont = new Font(bf, 10, Font.BOLD, BaseColor.WHITE); 
        
        // Tambah Header Kolom
        com.itextpdf.text.pdf.PdfPCell cell; // Gunakan PdfPCell untuk kustomisasi
        
        cell = new com.itextpdf.text.pdf.PdfPCell(new Paragraph("NIM", headerFont));
        cell.setBackgroundColor(BaseColor.DARK_GRAY);
        tbl.addCell(cell);
        
        cell = new com.itextpdf.text.pdf.PdfPCell(new Paragraph("Nama", headerFont));
        cell.setBackgroundColor(BaseColor.DARK_GRAY);
        tbl.addCell(cell);

        cell = new com.itextpdf.text.pdf.PdfPCell(new Paragraph("Alamat", headerFont));
        cell.setBackgroundColor(BaseColor.DARK_GRAY);
        tbl.addCell(cell);

        cell = new com.itextpdf.text.pdf.PdfPCell(new Paragraph("Kota", headerFont));
        cell.setBackgroundColor(BaseColor.DARK_GRAY);
        tbl.addCell(cell);


        // 5. Ambil Data dari Database dan isi tabel PDF
        String sql = "SELECT * FROM mahasiswa";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            tbl.addCell(rs.getString("nim"));
            tbl.addCell(rs.getString("nama"));
            tbl.addCell(rs.getString("alamat"));
            tbl.addCell(rs.getString("kota"));
        }

        // 6. Tambahkan tabel ke dokumen
        doc.add(tbl);
        
        JOptionPane.showMessageDialog(null, "Laporan PDF berhasil dibuat di:\n" + path + "\\LaporanMahasiswa.pdf", "Cetak Berhasil", JOptionPane.INFORMATION_MESSAGE);

    } catch (FileNotFoundException | DocumentException | SQLException ex) {
        JOptionPane.showMessageDialog(null, "Gagal Mencetak PDF: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (java.io.IOException ex) {
        JOptionPane.showMessageDialog(null, "Gagal Mencetak PDF: File/BaseFont Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // 7. Tutup dokumen
        if (doc != null && doc.isOpen()) {
            doc.close();
        }
    }
    }//GEN-LAST:event_BTcetakpdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTcetakpdf;
    private javax.swing.JButton BTedit;
    private javax.swing.JButton BThapus;
    private javax.swing.JButton BTsimpan;
    private javax.swing.JTable TBmahasiswa;
    private javax.swing.JTextField TFalamat;
    private javax.swing.JTextField TFkota;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFnim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    // Bagian paling bawah kelas FormMahasiswa
private void bersihkanForm() {
    // Kosongkan semua Text Field
    TFnim.setText("");
    TFnama.setText("");
    TFalamat.setText("");
    TFkota.setText("");
    
    // Pastikan TFnim bisa diisi lagi (jika sebelumnya dinonaktifkan untuk edit)
    TFnim.setEditable(true); 
    }
}
